Name:           ros-melodic-mrpt-bridge
Version:        0.1.22
Release:        0%{?dist}
Summary:        ROS mrpt_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/mrpt_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-marker-msgs
Requires:       ros-melodic-message-generation
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-mrpt-msgs
Requires:       ros-melodic-mrpt1
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-stereo-msgs
Requires:       ros-melodic-tf
BuildRequires:  gtest-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-marker-msgs
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-message-runtime
BuildRequires:  ros-melodic-mrpt-msgs
BuildRequires:  ros-melodic-mrpt1
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-pcl-conversions
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-stereo-msgs
BuildRequires:  ros-melodic-tf

%description
C++ libraries to convert between ROS and MRPT classes and messages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri May 18 2018 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.1.22-0
- Autogenerated by Bloom

